### ISSUE TITLE
Remote Flipper app android

### ISSUE THREAD

**Issue by Kzy07** [RogueMaster/flipperzero-firmware-wPlugins#636] opened 2023-05-17 17:46 UTC
### Describe the bug.

Since the last 3 updates, I can no longer remote control flipper from the Android app,
- sub-ghz not working
- rfid not working
- nfc works
- iBUTTON not working to remote control

### Reproduction

Android app
Archive
Sub-ghz file
'My file'
Send
Not remote flipper from app android

### Target

Flipper

**Comment by RogueMaster** [comment] 2023-05-17 21:25
Can you post a video of what you are trying to do?

Can you pair your Android device to flipper?

What SubGHz file is not working? I have confirmed SubGHz sends working on Flipper.

What RFID file is not working? I can confirm RFID is still working on Flipper.

**Comment by Kzy07** [comment] 2023-05-18 00:07
https://www.mediafire.com/file/k3guaam0r4hq9sc/IMG_0195.MOV/file



flipper and Android pairing is ok

flipper work perfectly 

Problem is remote control flipper from android, look my video. Sorry my English is bad.

**Comment by RogueMaster** [comment] 2023-05-18 06:13
This is likely due to renamed SubGHz and RFID apps so the app doesn't know how to launch these files. This is an issue with the app, kind of. The firmware will still work to play the files, you just need to navigate the firmware from the phone instead of trying to use the file shortcut. I'm open to ideas on how to fix this. Renaming SubGHz or RFID back to original names would cause them to show cut off on the Wii Menu view...

**Comment by RogueMaster** [comment] 2023-05-18 06:51
Should be fixed with https://github.com/RogueMaster/flipperzero-firmware-wPlugins/commit/7506ec92059eae9f630b111be350bb636fd702ce if you can, compile and test. Thank you!

**Closed as completed by RogueMaster** 2023-05-18 06:51 UTC
Labels: bug, help wanted

**Comment by Kzy07** [comment] 2023-05-18 13:13
Hello, I just compiled. the problem is solved except for ibutton. thank you for your good work

**Comment by Kzy07** [comment] 2023-05-18 21:43
i just compiled 1889ec1 ibutton not work
