### ISSUE TITLE
Flipper won’t boot and blinks after update 

### ISSUE THREAD

**Issue by FoxLy1312** [RogueMaster/flipperzero-firmware-wPlugins#606] opened 2023-04-21 02:36 UTC
### Describe the bug.

New building wont boot and needed dfu repair sequence to recover twice. 

### Reproduction

Build Repo
Updated to current official Software
Delate Apps folder 
Browse  and install RM-update
?
Blinking Boot loop
Repeat

**Comment by RogueMaster** [comment] 2023-04-21 07:54
This is fixed on latest code for the time being... the cause of the radio FW update causing the boot loops is still unknown...

**Closed by RogueMaster** 2023-04-21 07:54 UTC
Labels: bug
