### ISSUE TITLE
Merge few interesting repositories

### ISSUE THREAD

**Issue by utenus** [RogueMaster/flipperzero-firmware-wPlugins#585] opened 2023-03-30 13:35 UTC
### Describe the enhancement you're suggesting.

I think it would be worth adding functionalities from these projects
https://github.com/IamUSER/Flipper-Fusion
https://github.com/BadException/Flipper-Xtreme
https://github.com/anfractuosity/flipperscope
https://github.com/quen0n/unitemp-flipperzero

**Comment by RogueMaster** [comment] 2023-03-30 14:24
The last two are already merged... the first two are xtreme forks, what about them makes them great to you?

**Closed as completed by RogueMaster** 2023-03-30 14:24 UTC

**Comment by utenus** [comment] 2023-03-30 15:39
Even the better work of Bad-KB, because there is no such function in the RogueMaster software at all.
NSFW Animations are also a fun addition.
Impersonating Apple AirTag because there is no such function in RogueMaster either.

Of course, a huge amount of additional resources, but I already wrote about it in your second repo dedicated to resources by editing README.md, e.g. SubGHz, a large number of collected signals.

Additional battery health themes.
A nice useful function called "TouchTunes", which I haven't seen here in RogueMaster and it's helpfull.

**Comment by RogueMaster** [comment] 2023-03-30 15:53
BadKB is still buggy and once bugs are out, they will PR to unleashed and it can get added to RM.
NSFW animations are not added by design, it will remain that way. I release an 18+ release on Patreon for those that want it.
Impersonating air tag is not actually working correctly, yet. If they led you to believe it works, try it out and see.

Additional signals are also not included by design. It creates a larger file for firmware install that is not necessary. Many of those other signals are jamming that will not be provided by RM. The ones that aren't jamming are all in my additional assets for Patreon's or in the Awesome Repo I provide.

TouchTunes is a very old app replaced by subghz remote. It is provided as a remote config file for subghz remote.
